package com.lic.package.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

public interface ApponinteeRepository extends JpaRepository<Apponintee, Long> {

    @Modifying
    @Query(value = "INSERT INTO POLICY_SRV_MBR_APOTE (APPOINTEE_ID, APPOINTEE_AADHAR_NUMBER, APPOINTEE_ACCOUNT_NUMBER, APPOINTEE_ACCOUNT_TYPE, APPOINTEE_CODE, APPOINTEE_NAME, APPOINTEE_BANK_NAME, CONTACT_NUMBER, CREATED_BY, CREATED_ON, DATE_OF_BIRTH, APPOINTEE_IFSC_CODE, IS_ACTIVE, MEMBER_ID, APPOINTEE_PAN, RELATIONSHIP) VALUES (:APPOINTEE_ID, :APPOINTEE_AADHAR_NUMBER, :APPOINTEE_ACCOUNT_NUMBER, :APPOINTEE_ACCOUNT_TYPE, :APPOINTEE_CODE, :APPOINTEE_NAME, :APPOINTEE_BANK_NAME, :CONTACT_NUMBER, :CREATED_BY, CURRENT_TIMESTAMP, :DATE_OF_BIRTH, :APPOINTEE_IFSC_CODE, :IS_ACTIVE, :MEMBER_ID, :APPOINTEE_PAN, :RELATIONSHIP)", nativeQuery = true)
    void createNewAppointee(@Param("APPOINTEE_ID") Long APPOINTEE_ID, @Param("APPOINTEE_AADHAR_NUMBER") String APPOINTEE_AADHAR_NUMBER, @Param("APPOINTEE_ACCOUNT_NUMBER") String APPOINTEE_ACCOUNT_NUMBER, @Param("APPOINTEE_ACCOUNT_TYPE")String APPOINTEE_ACCOUNT_TYPE, @Param("APPOINTEE_CODE") String APPOINTEE_CODE, @Param("APPOINTEE_NAME") String APPOINTEE_NAME, @Param("APPOINTEE_BANK_NAME") String APPOINTEE_BANK_NAME, @Param("CONTACT_NUMBER") String CONTACT_NUMBER, @Param("CREATED_BY") Long CREATED_BY, @Param("DATE_OF_BIRTH") String DATE_OF_BIRTH, @Param("APPOINTEE_IFSC_CODE") String APPOINTEE_IFSC_CODE, @Param("IS_ACTIVE") Boolean IS_ACTIVE, @Param("MEMBER_ID") Long MEMBER_ID, @Param("APPOINTEE_PAN") String APPOINTEE_PAN, @Param("RELATIONSHIP") String RELATIONSHIP);

    @Modifying
    @Query(value = "UPDATE POLICY_SRV_MBR_APOTE SET APPOINTEE_AADHAR_NUMBER = :APPOINTEE_AADHAR_NUMBER, APPOINTEE_ACCOUNT_NUMBER = :APPOINTEE_ACCOUNT_NUMBER, APPOINTEE_ACCOUNT_TYPE = :APPOINTEE_ACCOUNT_TYPE, APPOINTEE_CODE = :APPOINTEE_CODE, APPOINTEE_NAME = :APPOINTEE_NAME, APPOINTEE_BANK_NAME = :APPOINTEE_BANK_NAME, CONTACT_NUMBER = :CONTACT_NUMBER, DATE_OF_BIRTH = :DATE_OF_BIRTH, APPOINTEE_IFSC_CODE = :APPOINTEE_IFSC_CODE, IS_ACTIVE = :IS_ACTIVE, MEMBER_ID = :MEMBER_ID, APPOINTEE_PAN = :APPOINTEE_PAN, RELATIONSHIP = :RELATIONSHIP, MODIFIED_BY = :MODIFIED_BY, MODIFIED_ON = CURRENT_TIMESTAMP WHERE APPOINTEE_ID = :APPOINTEE_ID", nativeQuery = true)
    void