landline_no, communication_preference = :communication_preference, language_preference = :language_preference, date_of_joining = :date_of_joining, date_of_joining_scheme = :date_of_joining_scheme, date_of_retirement = :date_of_retirement, membership_number = :membership_number, member_pan = :member_pan, member_status = :member_status, is_zero = :is_zero, is_active = :is_active, created_by = :created_by, modified_by = :modified_by, spouse_name = :spouse_name WHERE id = :id")
	public void updateMemberDetails(@Param("id") Integer id, @Param("policy_id") Integer policy_id, @Param("type_of_membership") String type_of_membership, @Param("category_no") String category_no, @Param("aadhar_number") String aadhar_number, @Param("first_name") String first_name, @Param("middle_name") String middle_name, @Param("last_name") String last_name, @Param("date_of_birth") String date_of_birth, @Param("father_name") String father_name, @Param("gender") String gender, @Param("marital_status") String marital_status, @Param("mobile_no") String mobile_no, @Param("email_id") String email_id, @Param("landline_no") String landline_no, @Param("communication_preference") String communication_preference, @Param("language_preference") String language_preference, @Param("date_of_joining") String date_of_joining, @Param("date_of_joining_scheme") String date_of_joining_scheme, @Param("date_of_retirement") String date_of_retirement, @Param("membership_number") String membership_number, @Param("member_pan") String member_pan, @Param("member_status") String member_status, @Param("is_zero") String is_zero, @Param("is_active") String is_active, @Param("created_by") String created_by, @Param("modified_by") String modified_by, @Param("spouse_name") String spouse_name);

	// Saving Member Address
	@Query("INSERT INTO PolicySrvMbrAdd (id, address_type, address_line_1, address_line_2, address_line_3, city, state, country, zip_code) "
	+ "VALUES (:id, :address_type, :address_line_1, :address_line_2, :address_line_3, :city, :state, :country, :zip_code)")
	public void saveMemberAddress(@Param("id") Integer id, @Param("address_type") String address_type, @Param("address_line_1") String address_line_1, @Param("address_line_2") String address_line_2, @Param("address_line_3") String address_line_3, @Param("city") String city, @Param("state") String state, @Param("country") String country, @Param("zip_code") String zip_code);

	// Updating Member Address
	@Query("UPDATE PolicySrvMbrAdd SET address_type = :address_type, address_line_1 = :address_line_1, address_line_2 = :address_line_2, address_line_3 = :address_line_3, city = :city, state = :state, country = :country, zip_code = :zip_code WHERE id = :id")
	public void updateMemberAddress(@Param("id") Integer id, @Param("address_type") String address_type, @Param("address_line_1") String address_line_1, @Param("address_line_2") String address_line_2, @Param("address_line_3") String address_line_3, @Param("city") String city, @Param("state") String state, @Param("country") String country, @Param("zip_code") String zip_code);

	// Saving Member Bank Details
	@Query("INSERT INTO PolicySrvMbrBank (id, bank_name, bank_account_number, branch_name, ifsc_code, micr_code, bank_address) "
	+ "VALUES (: