package com.lic.package.service;

import java.util.Date;
import java.util.List;
import java.util.Optional;

import com.lic.package.model.POLICY_SRV_MBR;
import com.lic.package.repository.MemberDetailsRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class MemberDetailsService {

    @Autowired
    MemberDetailsRepository memberDetailsRepository;

    public Optional<POLICY_SRV_MBR> findByMemberId(Long memberId) {
        return memberDetailsRepository.findByMemberId(memberId);
    }

    public Optional<POLICY_SRV_MBR> findByAadharNumber(String aadharNumber) {
        return memberDetailsRepository.findByAadharNumber(aadharNumber);
    }

    public List<POLICY_SRV_MBR> findByCategoryNumberAndCommunicationPreferenceAndCreatedByAndCreatedOnAndDateOfBirthAndDateOfJoiningAndDateOfJoiningSchemeAndDateOfRetirementAndDesignationAndEmailAddressAndFathersNameAndFirstNameAndGenderAndIsActiveAndIsZeroIdAndLandlineNumberAndLanguagePreferenceAndLastNameAndLICIdAndMaritalStatusAndMemberAdditionIdAndMemberPANAndMemberStatusAndMembershipNumberAndMiddleNameAndMobileNumberAndModifiedByAndModifiedOnAndPolicyIdAndSpouseNameAndTypeOfMembershipAndAnnuityOptionAndBatchIdAndCategoryAndEmployeeContributionAndEmployerContributionAndFrequencyAndMPHCodeAndMPHNameAndPANAndPhoneNumberAndPolicyNumberAndPolicyStatusAndProductAndQuotationIdAndQuotationTypeAndReferenceLICIdAndRoleAndServiceIdAndServiceNumberAndServiceStatusAndTotalContributionAndTotalInterestedAccruedAndUnitCodeAndVoluntaryContributionAndMembershipId(String categoryNumber, String communicationPreference, String createdBy, Date createdOn, Date dateOfBirth, Date dateOfJoining, Date dateOfJoiningScheme, Date dateOfRetirement, String designation, String emailAddress, String fathersName, String firstName, String gender, Integer isActive, Integer isZeroId, String landlineNumber, String languagePreference, String lastName, String lICId, String maritalStatus, String memberAdditionId, String memberPAN, String memberStatus, String membershipNumber, String middleName, String mobileNumber, String modifiedBy, Date modifiedOn, String policyId, String spouseName, String typeOfMembership, String annuityOption, String batchId, String category, Integer employeeContribution, Integer employerContribution, String frequency, String mPHCode, String mPHName, String pAN, String phoneNumber, String policyNumber, String policyStatus, String product, String quotationId, String quotationType, String referenceLICId, String role, String serviceId, String serviceNumber, String serviceStatus, Integer totalContribution, Integer totalInterestedAccrued, String unitCode, Integer voluntaryContribution, String membershipId) {
        return memberDetailsRepository.findByCategoryNumberAndCommunicationPreferenceAndCreatedByAndCreatedOnAndDateOfBirthAndDateOfJoiningAndDateOfJoiningSchemeAndDateOfRetirementAndDesignationAndEmailAddressAndFathersNameAndFirstNameAndGenderAndIsActiveAndIsZeroIdAndLandlineNumberAndLanguagePreferenceAndLastNameAndLICIdAndMaritalStatusAndMemberAdditionIdAndMemberPANAndMemberStatusAndMembershipNumberAndMiddleNameAndMobileNumberAndModifiedByAndModifiedOnAndPolicyIdAndSpouseNameAndTypeOfMembershipAndAnnuityOptionAndBatchIdAndCategoryAndEmployeeContributionAndEmployerContributionAndFrequencyAndMPHCodeAndMPHNameAndPANAndPhoneNumberAndPolicyNumberAndPolicyStatusAndProductAndQuotationIdAndQuotationTypeAndReferenceLICIdAndRoleAndServiceIdAndServiceNumberAndServiceStatusAndTotalContributionAndTotalInterestedAccruedAndUnitCodeAndVoluntaryContributionAndMembershipId(categoryNumber, communicationPreference, createdBy, createdOn, dateOfBirth, dateOfJoining, dateOfJoiningScheme, dateOfRetirement, designation, emailAddress, fathersName, firstName, gender, isActive, isZeroId, landlineNumber, languagePreference, lastName, lICId, maritalStatus, memberAdditionId, memberPAN, memberStatus, membershipNumber, middleName, mobileNumber, modifiedBy, modifiedOn, policyId